"""new column in secretsLog

Revision ID: 4db4bc0d95e4
Revises: c893fd9f0047
Create Date: 2025-04-29 18:03:55.809017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db4bc0d95e4'
down_revision: Union[str, None] = 'c893fd9f0047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets_log', sa.Column('ip_deleted_by', sa.String(), nullable=True))
    op.drop_column('secrets_log', 'ip_deleled_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets_log', sa.Column('ip_deleled_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('secrets_log', 'ip_deleted_by')
    # ### end Alembic commands ###
