"""new column in secretsLog

Revision ID: c893fd9f0047
Revises: 7089bd076fa4
Create Date: 2025-04-29 17:50:38.216603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c893fd9f0047'
down_revision: Union[str, None] = '7089bd076fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets_log', sa.Column('ip_deleled_by', sa.String(), nullable=True))
    op.add_column('secrets_log', sa.Column('ip_creator', sa.String(), nullable=True))
    op.drop_column('secrets_log', 'ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets_log', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('secrets_log', 'ip_creator')
    op.drop_column('secrets_log', 'ip_deleled_by')
    # ### end Alembic commands ###
